"""1

Revision ID: 63a59264d177
Revises: ce508d257840
Create Date: 2026-02-19 16:25:20.784177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a59264d177'
down_revision: Union[str, Sequence[str], None] = 'ce508d257840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('add_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markers', 'add_timestamp')
    # ### end Alembic commands ###
