"""1

Revision ID: 87ff2440e231
Revises: 63a59264d177
Create Date: 2026-02-19 16:52:01.779218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ff2440e231'
down_revision: Union[str, Sequence[str], None] = '63a59264d177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('all_day', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markers', 'all_day')
    # ### end Alembic commands ###
