# answers.py
I_AM_REGULAR = "Я одногруппник"
I_AM_ELDER = "Я староста"
I_AM_HERE_NOW = "✅ Отметиться на эту пару"
I_AM_HERE_TODAY = "✅🗓 Отметиться на весь день"
GET_CHECKS_NOW = "📋 Список на эту пару"
GET_CHECKS_TODAY = "📋🗓 Список на весь день"
GET_CHECKS_ON_DATE = "📋📆 Список на дату"
GET_CODE = "🔑Выдать код подключения"
# Кнопки для админки и расписания
SCHEDULE_SETTINGS = "⚙ Настройка расписания"
VIEW_SCHEDULE = "Посмотреть расписание"
EDIT_SCHEDULE = "Изменить расписание"       # если используется
BACK = "Назад"
ADD_LESSON = "➕ Добавить занятие"
REMOVE_LESSON = "❌ Удалить занятие"
SHOW_CURRENT = "📋 Показать текущее"
SAVE_AND_EXIT = "💾 Сохранить и выйти"
# CANCEL_CHANGES = "🚫 Отменить изменения"
RESTART = "Рестарт"
YES_CORRECT="Да, верно"
NO_INCORRECT="Нет, заново"
STOP = "Стоп"